"""GET /tickets/{ticket_id} — the TC-F/N/B table from the test plan.

Originally generated by the local Muse Glimmer model against a live server,
then converted to run the app in-process via the `client` fixture. The
assertions are unchanged from the generated versions.

GET /tickets/{ticket_id} requires a bearer token. Auth is a precondition of
every case in the table, so the `AUTH` header from conftest is the default;
TC-N04 (no header) and TC-N05 (wrong customer) override it deliberately.
"""

import pytest

from conftest import AUTH

pytestmark = pytest.mark.unit


# TC-F01 Functional Valid ticket retrieval
def test_tc_f01_valid_ticket_retrieval(client):
    path = "/tickets/123"
    headers = {"Authorization": "Bearer valid-token"}
    response = client.get(path, headers=headers)
    assert response.status_code == 200, "TC-F01: expected 200 OK"
    assert "application/json" in response.headers.get("Content-Type", ""), "TC-F01: expected Content-Type application/json"
    data = response.json()
    assert data.get("id") == 123, "TC-F01: expected body contains id=123"
    assert "status" in data, "TC-F01: expected status field present"
    assert "priority" in data, "TC-F01: expected priority field present"
    assert isinstance(data.get("customer"), dict), "TC-F01: expected customer object present"
    customer = data.get("customer", {})
    assert "id" in customer and "name" in customer and "email" in customer, "TC-F01: expected customer with id/name/email"


# TC-F02 Functional Response schema
def test_tc_f02_response_schema(client):
    path = "/tickets/123"
    response = client.get(path, headers=AUTH)
    assert response.status_code == 200, "TC-F02: expected 200 OK"
    data = response.json()
    assert "id" in data, "TC-F02: expected id field present"
    assert isinstance(data.get("id"), int), "TC-F02: expected id int"
    assert "status" in data, "TC-F02: expected status field present"
    assert isinstance(data.get("status"), str), "TC-F02: expected status string"
    assert "priority" in data, "TC-F02: expected priority field present"
    assert isinstance(data.get("priority"), str), "TC-F02: expected priority string"
    assert "customer" in data, "TC-F02: expected customer field present"
    assert isinstance(data.get("customer"), dict), "TC-F02: expected customer object"


# TC-N01 Negative Ticket not found
def test_tc_n01_ticket_not_found(client):
    path = "/tickets/999999"
    response = client.get(path, headers=AUTH)
    assert response.status_code == 404, "TC-N01: expected 404 Not Found"
    assert response.json() == {"detail": "Ticket not found"}, "TC-N01: expected body {\"detail\": \"Ticket not found\"}"


# TC-N02 Negative Invalid format - non numeric
def test_tc_n02_invalid_format_non_numeric(client):
    path = "/tickets/abc"
    response = client.get(path, headers=AUTH)
    assert response.status_code == 400, "TC-N02: expected 400 Bad Request"


# TC-N03 Negative Invalid format - special chars
def test_tc_n03_invalid_format_special_chars(client):
    path = "/tickets/123;DROP"
    response = client.get(path, headers=AUTH)
    assert response.status_code == 400, "TC-N03: expected 400 Bad Request"


# TC-N04 Negative Missing auth
def test_tc_n04_missing_auth(client):
    path = "/tickets/123"
    response = client.get(path)
    assert response.status_code == 401, "TC-N04: expected 401 Unauthorized"


# TC-N05 Negative Forbidden - wrong tenant/user
def test_tc_n05_forbidden_wrong_tenant(client):
    path = "/tickets/123"
    headers = {"Authorization": "Bearer userA"}
    response = client.get(path, headers=headers)
    assert response.status_code == 403, "TC-N05: expected 403 Forbidden"


# TC-B01 Boundary Minimum valid ID
def test_tc_b01_minimum_valid_id(client):
    path = "/tickets/1"
    response = client.get(path, headers=AUTH)
    assert response.status_code == 200, "TC-B01: expected 200 OK"


# TC-B02 Boundary Max int ID
def test_tc_b02_max_int_id(client):
    path = "/tickets/2147483647"
    response = client.get(path, headers=AUTH)
    assert response.status_code in (200, 404), "TC-B02: expected 200 OK or 404 if not exist, no overflow"


# TC-B03 Boundary Negative ID
def test_tc_b03_negative_id(client):
    path = "/tickets/-5"
    response = client.get(path, headers=AUTH)
    assert response.status_code == 400, "TC-B03: expected 400 Bad Request"


# TC-B04 Boundary Zero ID
def test_tc_b04_zero_id(client):
    path = "/tickets/0"
    response = client.get(path, headers=AUTH)
    assert response.status_code in (400, 404), "TC-B04: expected 400 or 404"


# TC-B05 Boundary UUID format if applicable
def test_tc_b05_uuid_format(client):
    path = "/tickets/00000000-0000-0000-0000-000000000000"
    response = client.get(path, headers=AUTH)
    assert response.status_code in (400, 404), "TC-B05: expected 400 if malformed UUID, 404 if well-formed but not found"
